In [1]:
import pandas as pd
import numpy as np
import os
from datetime import datetime, timedelta

In [2]:
os.getcwd()

'C:\\Users\\Zachary Brown\\Documents\\GitHub\\dsc\\relax_challenge'

In [3]:
users = pd.read_csv("takehome_users.csv", index_col='object_id', encoding='latin-1')

In [4]:
users.head()

creation_time               name                       email  \
object_id                                                                       
1          2014-04-22 03:53:30     Clausen August    AugustCClausen@yahoo.com   
2          2013-11-15 03:45:04      Poole Matthew      MatthewPoole@gustr.com   
3          2013-03-19 23:14:52  Bottrill Mitchell  MitchellBottrill@gustr.com   
4          2013-05-21 08:09:28    Clausen Nicklas   NicklasSClausen@yahoo.com   
5          2013-01-17 10:14:20          Raw Grace          GraceRaw@yahoo.com   

          creation_source  last_session_creation_time  \
object_id                                               
1            GUEST_INVITE                1.398139e+09   
2              ORG_INVITE                1.396238e+09   
3              ORG_INVITE                1.363735e+09   
4            GUEST_INVITE                1.369210e+09   
5            GUEST_INVITE                1.358850e+09   

           opted_in_to_mailing_list  enabled_for_marketing_drip  org_id  \
object_id                                                                 
1                                 1                           0      11   
2                                 0                           0       1   
3                                 0                           0      94   
4                                 0                           0       1   
5                                 0                           0     193   

           invited_by_user_id  
object_id                      
1                     10803.0  
2                       316.0  
3                      1525.0  
4                      5151.0  
5                      5240.0

In [5]:
engagement = pd.read_csv('takehome_user_engagement.csv')

In [6]:
engagement.head()

time_stamp  user_id  visited
0  2014-04-22 03:53:30        1        1
1  2013-11-15 03:45:04        2        1
2  2013-11-29 03:45:04        2        1
3  2013-12-09 03:45:04        2        1
4  2013-12-25 03:45:04        2        1

In [7]:
merged = engagement.join(users, on='user_id', how='inner')

In [8]:
merged.head()

time_stamp  user_id  visited        creation_time            name  \
0  2014-04-22 03:53:30        1        1  2014-04-22 03:53:30  Clausen August   
1  2013-11-15 03:45:04        2        1  2013-11-15 03:45:04   Poole Matthew   
2  2013-11-29 03:45:04        2        1  2013-11-15 03:45:04   Poole Matthew   
3  2013-12-09 03:45:04        2        1  2013-11-15 03:45:04   Poole Matthew   
4  2013-12-25 03:45:04        2        1  2013-11-15 03:45:04   Poole Matthew   

                      email creation_source  last_session_creation_time  \
0  AugustCClausen@yahoo.com    GUEST_INVITE                1.398139e+09   
1    MatthewPoole@gustr.com      ORG_INVITE                1.396238e+09   
2    MatthewPoole@gustr.com      ORG_INVITE                1.396238e+09   
3    MatthewPoole@gustr.com      ORG_INVITE                1.396238e+09   
4    MatthewPoole@gustr.com      ORG_INVITE                1.396238e+09   

   opted_in_to_mailing_list  enabled_for_marketing_drip  org_id  \
0                         1                           0      11   
1                         0                           0       1   
2                         0                           0       1   
3                         0                           0       1   
4                         0                           0       1   

   invited_by_user_id  
0             10803.0  
1               316.0  
2               316.0  
3               316.0  
4               316.0

In [9]:
merged.dtypes

time_stamp                     object
user_id                         int64
visited                         int64
creation_time                  object
name                           object
email                          object
creation_source                object
last_session_creation_time    float64
opted_in_to_mailing_list        int64
enabled_for_marketing_drip      int64
org_id                          int64
invited_by_user_id            float64
dtype: object

In [10]:
merged['time_stamp'] = pd.to_datetime(merged['time_stamp'])

In [11]:
merged.dtypes

time_stamp                    datetime64[ns]
user_id                                int64
visited                                int64
creation_time                         object
name                                  object
email                                 object
creation_source                       object
last_session_creation_time           float64
opted_in_to_mailing_list               int64
enabled_for_marketing_drip             int64
org_id                                 int64
invited_by_user_id                   float64
dtype: object

In [12]:
merged['creation_time'] = pd.to_datetime(merged['creation_time'])

In [13]:
merged['time_stamp'] = merged['time_stamp'].dt.floor('d').astype(np.int64)
dropped_dups = merged.sort_values(['user_id', 'time_stamp']).drop_duplicates()

In [14]:
roll = dropped_dups.groupby('user_id')['time_stamp'].rolling(window=3)
delta = pd.to_timedelta((roll.max()- roll.min())).dt.days

In [15]:
delta

user_id        
1        0          NaN
2        1          NaN
         2          NaN
         3         24.0
         4         26.0
                   ... 
11996    207912     NaN
11997    207913     NaN
11998    207914     NaN
11999    207915     NaN
12000    207916     NaN
Name: time_stamp, Length: 207917, dtype: float64

In [16]:
adopted = delta[delta < 8].index.get_level_values('user_id').tolist()

In [17]:
adopted

[2,
 2,
 2,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10,
 10

In [18]:
unique_adopted = []
for i in adopted:
    if i not in unique_adopted:
        unique_adopted.append(int(i))

In [19]:
unique_adopted

[2,
 10,
 20,
 33,
 42,
 43,
 50,
 53,
 60,
 63,
 69,
 74,
 80,
 81,
 82,
 87,
 133,
 135,
 141,
 146,
 153,
 160,
 165,
 168,
 172,
 174,
 185,
 188,
 197,
 200,
 202,
 203,
 209,
 214,
 230,
 245,
 247,
 263,
 265,
 275,
 280,
 283,
 297,
 298,
 305,
 310,
 311,
 321,
 322,
 341,
 345,
 347,
 351,
 362,
 363,
 370,
 383,
 397,
 401,
 418,
 430,
 445,
 450,
 460,
 462,
 469,
 471,
 472,
 478,
 479,
 483,
 492,
 494,
 497,
 502,
 506,
 509,
 510,
 512,
 518,
 520,
 522,
 529,
 535,
 540,
 547,
 553,
 564,
 572,
 589,
 591,
 601,
 603,
 605,
 618,
 627,
 628,
 632,
 634,
 639,
 669,
 679,
 680,
 717,
 724,
 725,
 728,
 754,
 772,
 783,
 786,
 804,
 828,
 845,
 851,
 869,
 874,
 882,
 885,
 901,
 906,
 907,
 912,
 928,
 932,
 934,
 937,
 943,
 953,
 980,
 985,
 1007,
 1009,
 1013,
 1017,
 1018,
 1026,
 1027,
 1035,
 1039,
 1055,
 1061,
 1072,
 1089,
 1093,
 1094,
 1099,
 1106,
 1107,
 1119,
 1123,
 1124,
 1128,
 1129,
 1136,
 1145,
 1150,
 1151,
 1155,
 1156,
 1163,
 1173,
 1186,
 1196,


In [20]:
merged['user_id'].unique()

array([    1,     2,     3, ..., 11998, 11999, 12000], dtype=int64)

In [21]:
merged['adopted'] = True

In [22]:
for user in merged['user_id'].unique():
    if user in unique_adopted:
        merged.loc[merged['user_id'] == user, 'adopted'] = True
    else:
        merged.loc[merged['user_id'] == user, 'adopted'] = False

In [23]:
merged['adopted'].value_counts()

True     198327
False      9590
Name: adopted, dtype: int64

In [24]:
dummied = pd.get_dummies(data = merged, columns=['creation_source', 'org_id'], drop_first=True)

In [25]:
dummied.columns.to_list()

['time_stamp',
 'user_id',
 'visited',
 'creation_time',
 'name',
 'email',
 'last_session_creation_time',
 'opted_in_to_mailing_list',
 'enabled_for_marketing_drip',
 'invited_by_user_id',
 'adopted',
 'creation_source_ORG_INVITE',
 'creation_source_PERSONAL_PROJECTS',
 'creation_source_SIGNUP',
 'creation_source_SIGNUP_GOOGLE_AUTH',
 'org_id_1',
 'org_id_2',
 'org_id_3',
 'org_id_4',
 'org_id_5',
 'org_id_6',
 'org_id_7',
 'org_id_8',
 'org_id_9',
 'org_id_10',
 'org_id_11',
 'org_id_12',
 'org_id_13',
 'org_id_14',
 'org_id_15',
 'org_id_16',
 'org_id_17',
 'org_id_18',
 'org_id_19',
 'org_id_20',
 'org_id_21',
 'org_id_22',
 'org_id_23',
 'org_id_24',
 'org_id_25',
 'org_id_26',
 'org_id_27',
 'org_id_28',
 'org_id_29',
 'org_id_30',
 'org_id_31',
 'org_id_32',
 'org_id_33',
 'org_id_34',
 'org_id_35',
 'org_id_36',
 'org_id_37',
 'org_id_38',
 'org_id_39',
 'org_id_40',
 'org_id_41',
 'org_id_42',
 'org_id_43',
 'org_id_44',
 'org_id_45',
 'org_id_46',
 'org_id_47',
 'org_id_48',


In [26]:
working = dummied.drop(columns=['time_stamp', 'user_id', 'creation_time', 'name', 'email', 'last_session_creation_time', 'invited_by_user_id'])

In [27]:
X = working.drop(columns=['adopted'])
y = working[['adopted']]

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [30]:
y_train = y_train.values.ravel()
y_test = y_test.values.ravel()

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
scaler = StandardScaler()
scaler.fit(X_train)
scaler.transform(X_train)
scaler.transform(X_test)

array([[ 0.        , -0.59013223, -0.42686714, ..., -0.02828853,
        -0.05733525, -0.00245195],
       [ 0.        , -0.59013223, -0.42686714, ..., -0.02828853,
        -0.05733525, -0.00245195],
       [ 0.        , -0.59013223, -0.42686714, ..., -0.02828853,
        -0.05733525, -0.00245195],
       ...,
       [ 0.        , -0.59013223,  2.34264927, ..., -0.02828853,
        -0.05733525, -0.00245195],
       [ 0.        , -0.59013223, -0.42686714, ..., -0.02828853,
        -0.05733525, -0.00245195],
       [ 0.        ,  1.69453549, -0.42686714, ..., -0.02828853,
        -0.05733525, -0.00245195]])

In [33]:
from sklearn.impute import SimpleImputer

In [34]:
imp = SimpleImputer(strategy='most_frequent')
imp.fit(X_train)
imp.transform(X_train)
imp.transform(X_test)

C:\Users\Zachary Brown\anaconda3\lib\site-packages\sklearn\impute\_base.py:49: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode = stats.mode(array)


array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix

In [36]:
parameters = {'max_depth': [3, 5, 7, 10], 'n_estimators': [50, 100, 200]}

rfc = RandomForestClassifier(random_state=15)
gscv = GridSearchCV(rfc, parameters, scoring = 'f1')
gscv.fit(X_train, y_train)
gscv.best_score_

0.9764501003193548

In [37]:
gscv.best_params_

{'max_depth': 3, 'n_estimators': 50}

In [38]:
rand = RandomForestClassifier(max_depth = 3, n_estimators = 50, random_state = 15)
rand.fit(X_train, y_train)
y_pred = rand.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[    0,  1936],
       [    0, 39648]], dtype=int64)

In [40]:
imp = pd.DataFrame({'feature':X_train.columns, 'importance':rand.feature_importances_})

In [43]:
imp.sort_values(by='importance', ascending=False).head(10)

feature  importance
285                  org_id_279    0.070649
1      opted_in_to_mailing_list    0.054890
12                     org_id_6    0.053942
305                  org_id_299    0.047425
352                  org_id_346    0.045705
3    creation_source_ORG_INVITE    0.044134
400                  org_id_394    0.042344
243                  org_id_237    0.040593
248                  org_id_242    0.036797
402                  org_id_396    0.032372